apiVersion: v1
kind: Secret
metadata:
  name: sre-challenge-db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNDU2Nzg=
  MYSQL_DATABASE: ZW1w
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: MTIzNDU2Nzg=